// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: rider/v1/rider.proto

package riderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRiderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRiderRequest) Reset() {
	*x = CreateRiderRequest{}
	mi := &file_rider_v1_rider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRiderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRiderRequest) ProtoMessage() {}

func (x *CreateRiderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rider_v1_rider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRiderRequest.ProtoReflect.Descriptor instead.
func (*CreateRiderRequest) Descriptor() ([]byte, []int) {
	return file_rider_v1_rider_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRiderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRiderRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateRiderRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateRiderRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type CreateRiderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRiderResponse) Reset() {
	*x = CreateRiderResponse{}
	mi := &file_rider_v1_rider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRiderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRiderResponse) ProtoMessage() {}

func (x *CreateRiderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rider_v1_rider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRiderResponse.ProtoReflect.Descriptor instead.
func (*CreateRiderResponse) Descriptor() ([]byte, []int) {
	return file_rider_v1_rider_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRiderResponse) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

type GetRiderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiderRequest) Reset() {
	*x = GetRiderRequest{}
	mi := &file_rider_v1_rider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiderRequest) ProtoMessage() {}

func (x *GetRiderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rider_v1_rider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiderRequest.ProtoReflect.Descriptor instead.
func (*GetRiderRequest) Descriptor() ([]byte, []int) {
	return file_rider_v1_rider_proto_rawDescGZIP(), []int{2}
}

func (x *GetRiderRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

type GetRiderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiderResponse) Reset() {
	*x = GetRiderResponse{}
	mi := &file_rider_v1_rider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiderResponse) ProtoMessage() {}

func (x *GetRiderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rider_v1_rider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiderResponse.ProtoReflect.Descriptor instead.
func (*GetRiderResponse) Descriptor() ([]byte, []int) {
	return file_rider_v1_rider_proto_rawDescGZIP(), []int{3}
}

func (x *GetRiderResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRiderResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetRiderResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetRiderResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

var File_rider_v1_rider_proto protoreflect.FileDescriptor

const file_rider_v1_rider_proto_rawDesc = "" +
	"\n" +
	"\x14rider/v1/rider.proto\x12\brider.v1\"p\n" +
	"\x12CreateRiderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\"0\n" +
	"\x13CreateRiderResponse\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\",\n" +
	"\x0fGetRiderRequest\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\"n\n" +
	"\x10GetRiderResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage2\x9d\x01\n" +
	"\fRiderService\x12J\n" +
	"\vCreateRider\x12\x1c.rider.v1.CreateRiderRequest\x1a\x1d.rider.v1.CreateRiderResponse\x12A\n" +
	"\bGetRider\x12\x19.rider.v1.GetRiderRequest\x1a\x1a.rider.v1.GetRiderResponseB9Z7github.com/lhiradi/ride-handling/proto/rider/v1;riderv1b\x06proto3"

var (
	file_rider_v1_rider_proto_rawDescOnce sync.Once
	file_rider_v1_rider_proto_rawDescData []byte
)

func file_rider_v1_rider_proto_rawDescGZIP() []byte {
	file_rider_v1_rider_proto_rawDescOnce.Do(func() {
		file_rider_v1_rider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rider_v1_rider_proto_rawDesc), len(file_rider_v1_rider_proto_rawDesc)))
	})
	return file_rider_v1_rider_proto_rawDescData
}

var file_rider_v1_rider_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rider_v1_rider_proto_goTypes = []any{
	(*CreateRiderRequest)(nil),  // 0: rider.v1.CreateRiderRequest
	(*CreateRiderResponse)(nil), // 1: rider.v1.CreateRiderResponse
	(*GetRiderRequest)(nil),     // 2: rider.v1.GetRiderRequest
	(*GetRiderResponse)(nil),    // 3: rider.v1.GetRiderResponse
}
var file_rider_v1_rider_proto_depIdxs = []int32{
	0, // 0: rider.v1.RiderService.CreateRider:input_type -> rider.v1.CreateRiderRequest
	2, // 1: rider.v1.RiderService.GetRider:input_type -> rider.v1.GetRiderRequest
	1, // 2: rider.v1.RiderService.CreateRider:output_type -> rider.v1.CreateRiderResponse
	3, // 3: rider.v1.RiderService.GetRider:output_type -> rider.v1.GetRiderResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rider_v1_rider_proto_init() }
func file_rider_v1_rider_proto_init() {
	if File_rider_v1_rider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rider_v1_rider_proto_rawDesc), len(file_rider_v1_rider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rider_v1_rider_proto_goTypes,
		DependencyIndexes: file_rider_v1_rider_proto_depIdxs,
		MessageInfos:      file_rider_v1_rider_proto_msgTypes,
	}.Build()
	File_rider_v1_rider_proto = out.File
	file_rider_v1_rider_proto_goTypes = nil
	file_rider_v1_rider_proto_depIdxs = nil
}
