// proto/trip/v1/trip.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: trip/v1/trip.proto

package tripv1

import (
	v1 "github.com/lhiradi/ride-handling/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RiderId       string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"` // empty until assigned
	Pickup        *v1.GeoPoint           `protobuf:"bytes,4,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *v1.GeoPoint           `protobuf:"bytes,5,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	Status        v1.TripStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=common.v1.TripStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trip) Reset() {
	*x = Trip{}
	mi := &file_trip_v1_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trip) ProtoMessage() {}

func (x *Trip) ProtoReflect() protoreflect.Message {
	mi := &file_trip_v1_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trip.ProtoReflect.Descriptor instead.
func (*Trip) Descriptor() ([]byte, []int) {
	return file_trip_v1_trip_proto_rawDescGZIP(), []int{0}
}

func (x *Trip) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trip) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *Trip) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Trip) GetPickup() *v1.GeoPoint {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *Trip) GetDropoff() *v1.GeoPoint {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *Trip) GetStatus() v1.TripStatus {
	if x != nil {
		return x.Status
	}
	return v1.TripStatus(0)
}

type CreateTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RiderId       string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	Pickup        *v1.GeoPoint           `protobuf:"bytes,2,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *v1.GeoPoint           `protobuf:"bytes,3,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // idempotency key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripRequest) Reset() {
	*x = CreateTripRequest{}
	mi := &file_trip_v1_trip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripRequest) ProtoMessage() {}

func (x *CreateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_v1_trip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripRequest.ProtoReflect.Descriptor instead.
func (*CreateTripRequest) Descriptor() ([]byte, []int) {
	return file_trip_v1_trip_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTripRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *CreateTripRequest) GetPickup() *v1.GeoPoint {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *CreateTripRequest) GetDropoff() *v1.GeoPoint {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *CreateTripRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CreateTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trip          *Trip                  `protobuf:"bytes,1,opt,name=trip,proto3" json:"trip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripResponse) Reset() {
	*x = CreateTripResponse{}
	mi := &file_trip_v1_trip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripResponse) ProtoMessage() {}

func (x *CreateTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_v1_trip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripResponse.ProtoReflect.Descriptor instead.
func (*CreateTripResponse) Descriptor() ([]byte, []int) {
	return file_trip_v1_trip_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTripResponse) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

type UpdateTripStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        v1.TripStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=common.v1.TripStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTripStatusRequest) Reset() {
	*x = UpdateTripStatusRequest{}
	mi := &file_trip_v1_trip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTripStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTripStatusRequest) ProtoMessage() {}

func (x *UpdateTripStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_v1_trip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTripStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTripStatusRequest) Descriptor() ([]byte, []int) {
	return file_trip_v1_trip_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTripStatusRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *UpdateTripStatusRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateTripStatusRequest) GetStatus() v1.TripStatus {
	if x != nil {
		return x.Status
	}
	return v1.TripStatus(0)
}

type GetTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripRequest) Reset() {
	*x = GetTripRequest{}
	mi := &file_trip_v1_trip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripRequest) ProtoMessage() {}

func (x *GetTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trip_v1_trip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripRequest.ProtoReflect.Descriptor instead.
func (*GetTripRequest) Descriptor() ([]byte, []int) {
	return file_trip_v1_trip_proto_rawDescGZIP(), []int{4}
}

func (x *GetTripRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type GetTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trip          *Trip                  `protobuf:"bytes,1,opt,name=trip,proto3" json:"trip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripResponse) Reset() {
	*x = GetTripResponse{}
	mi := &file_trip_v1_trip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripResponse) ProtoMessage() {}

func (x *GetTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trip_v1_trip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripResponse.ProtoReflect.Descriptor instead.
func (*GetTripResponse) Descriptor() ([]byte, []int) {
	return file_trip_v1_trip_proto_rawDescGZIP(), []int{5}
}

func (x *GetTripResponse) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

var File_trip_v1_trip_proto protoreflect.FileDescriptor

const file_trip_v1_trip_proto_rawDesc = "" +
	"\n" +
	"\x12trip/v1/trip.proto\x12\atrip.v1\x1a\x16common/v1/common.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd9\x01\n" +
	"\x04Trip\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12+\n" +
	"\x06pickup\x18\x04 \x01(\v2\x13.common.v1.GeoPointR\x06pickup\x12-\n" +
	"\adropoff\x18\x05 \x01(\v2\x13.common.v1.GeoPointR\adropoff\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.common.v1.TripStatusR\x06status\"\xa9\x01\n" +
	"\x11CreateTripRequest\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12+\n" +
	"\x06pickup\x18\x02 \x01(\v2\x13.common.v1.GeoPointR\x06pickup\x12-\n" +
	"\adropoff\x18\x03 \x01(\v2\x13.common.v1.GeoPointR\adropoff\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"7\n" +
	"\x12CreateTripResponse\x12!\n" +
	"\x04trip\x18\x01 \x01(\v2\r.trip.v1.TripR\x04trip\"~\n" +
	"\x17UpdateTripStatusRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.common.v1.TripStatusR\x06status\")\n" +
	"\x0eGetTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\"4\n" +
	"\x0fGetTripResponse\x12!\n" +
	"\x04trip\x18\x01 \x01(\v2\r.trip.v1.TripR\x04trip2\xe0\x01\n" +
	"\vTripService\x12E\n" +
	"\n" +
	"CreateTrip\x12\x1a.trip.v1.CreateTripRequest\x1a\x1b.trip.v1.CreateTripResponse\x12L\n" +
	"\x10UpdateTripStatus\x12 .trip.v1.UpdateTripStatusRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\aGetTrip\x12\x17.trip.v1.GetTripRequest\x1a\x18.trip.v1.GetTripResponseB7Z5github.com/lhiradi/ride-handling/proto/trip/v1;tripv1b\x06proto3"

var (
	file_trip_v1_trip_proto_rawDescOnce sync.Once
	file_trip_v1_trip_proto_rawDescData []byte
)

func file_trip_v1_trip_proto_rawDescGZIP() []byte {
	file_trip_v1_trip_proto_rawDescOnce.Do(func() {
		file_trip_v1_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trip_v1_trip_proto_rawDesc), len(file_trip_v1_trip_proto_rawDesc)))
	})
	return file_trip_v1_trip_proto_rawDescData
}

var file_trip_v1_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_trip_v1_trip_proto_goTypes = []any{
	(*Trip)(nil),                    // 0: trip.v1.Trip
	(*CreateTripRequest)(nil),       // 1: trip.v1.CreateTripRequest
	(*CreateTripResponse)(nil),      // 2: trip.v1.CreateTripResponse
	(*UpdateTripStatusRequest)(nil), // 3: trip.v1.UpdateTripStatusRequest
	(*GetTripRequest)(nil),          // 4: trip.v1.GetTripRequest
	(*GetTripResponse)(nil),         // 5: trip.v1.GetTripResponse
	(*v1.GeoPoint)(nil),             // 6: common.v1.GeoPoint
	(v1.TripStatus)(0),              // 7: common.v1.TripStatus
	(*emptypb.Empty)(nil),           // 8: google.protobuf.Empty
}
var file_trip_v1_trip_proto_depIdxs = []int32{
	6,  // 0: trip.v1.Trip.pickup:type_name -> common.v1.GeoPoint
	6,  // 1: trip.v1.Trip.dropoff:type_name -> common.v1.GeoPoint
	7,  // 2: trip.v1.Trip.status:type_name -> common.v1.TripStatus
	6,  // 3: trip.v1.CreateTripRequest.pickup:type_name -> common.v1.GeoPoint
	6,  // 4: trip.v1.CreateTripRequest.dropoff:type_name -> common.v1.GeoPoint
	0,  // 5: trip.v1.CreateTripResponse.trip:type_name -> trip.v1.Trip
	7,  // 6: trip.v1.UpdateTripStatusRequest.status:type_name -> common.v1.TripStatus
	0,  // 7: trip.v1.GetTripResponse.trip:type_name -> trip.v1.Trip
	1,  // 8: trip.v1.TripService.CreateTrip:input_type -> trip.v1.CreateTripRequest
	3,  // 9: trip.v1.TripService.UpdateTripStatus:input_type -> trip.v1.UpdateTripStatusRequest
	4,  // 10: trip.v1.TripService.GetTrip:input_type -> trip.v1.GetTripRequest
	2,  // 11: trip.v1.TripService.CreateTrip:output_type -> trip.v1.CreateTripResponse
	8,  // 12: trip.v1.TripService.UpdateTripStatus:output_type -> google.protobuf.Empty
	5,  // 13: trip.v1.TripService.GetTrip:output_type -> trip.v1.GetTripResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_trip_v1_trip_proto_init() }
func file_trip_v1_trip_proto_init() {
	if File_trip_v1_trip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trip_v1_trip_proto_rawDesc), len(file_trip_v1_trip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trip_v1_trip_proto_goTypes,
		DependencyIndexes: file_trip_v1_trip_proto_depIdxs,
		MessageInfos:      file_trip_v1_trip_proto_msgTypes,
	}.Build()
	File_trip_v1_trip_proto = out.File
	file_trip_v1_trip_proto_goTypes = nil
	file_trip_v1_trip_proto_depIdxs = nil
}
